SELECT DISTINCT * FROM(SELECT
	DISTINCT
	--	CLIENTE
	(T1."CardCode" || '#'  ||
	IFNULL(T3."BlockS",'SIN BARRIO') || '#' ||
IFNULL(T5."U_HBT_MunMed",'54001')) AS "Clientes"
--	DOCUMENTO
FROM
	"HBTGELVEZ_CUCUTA"."OINV" T1
INNER JOIN
	"HBTGELVEZ_CUCUTA"."INV1" T2
		ON T1."DocEntry" = T2."DocEntry"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."INV12" T3
		ON T1."DocEntry" = T3."DocEntry"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."NNM1" T4
		ON T1."Series" = T4."Series"
--	CLIENTE
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OCRD" T5
		ON T1."CardCode" = T5."CardCode"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OCRG" T6
		ON T5."GroupCode" = T6."GroupCode"
--	PRODUCTO
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OITM" T7
		ON T2."ItemCode" = T7."ItemCode"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OITB" T8
		ON T7."ItmsGrpCod" = T8."ItmsGrpCod"
LEFT JOIN
	"HBTGELVEZ_CUCUTA"."@GD_SUBGRUPO" T9
		ON T7."U_GD_SubGrupo" = T9."Code"
LEFT JOIN
	"HBTGELVEZ_CUCUTA"."@GD_FAMPRODUCTOS" T10
		ON T7."U_GD_FamProducto" = T10."Code"
--	VENDEDOR
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OSLP" T11
		ON T1."SlpCode" = T11."SlpCode"
WHERE
--T1."DocDate" BETWEEN '[%0]' AND '[%1]'
T1."DocDate" BETWEEN {0}--ADD_DAYS(LAST_DAY(ADD_MONTHS(CURRENT_DATE, -{0})),+1) AND  ADD_DAYS(TO_VARCHAR(CURRENT_DATE,'YYYYMMDD'), -1 )
AND T2."WhsCode" in ('006','030')

UNION ALL

SELECT
	DISTINCT
	--	CLIENTE
	(T1."CardCode" || '#'  ||
	IFNULL(T3."BlockS",'SIN BARRIO') || '#' ||
IFNULL(T5."U_HBT_MunMed",'54001')) AS "Clientes"
--	DOCUMENTO
FROM
	"HBTGELVEZ_CUCUTA"."ORIN" T1
INNER JOIN
	"HBTGELVEZ_CUCUTA"."RIN1" T2
		ON T1."DocEntry" = T2."DocEntry"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."RIN12" T3
		ON T1."DocEntry" = T3."DocEntry"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."NNM1" T4
		ON T1."Series" = T4."Series"
--	CLIENTE
INNER JOIN
    "HBTGELVEZ_CUCUTA"."OCRD" T5
		ON T1."CardCode" = T5."CardCode"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OCRG" T6
		ON T5."GroupCode" = T6."GroupCode"
--	PRODUCTO
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OITM" T7
		ON T2."ItemCode" = T7."ItemCode"
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OITB" T8
		ON T7."ItmsGrpCod" = T8."ItmsGrpCod"
LEFT JOIN
	"HBTGELVEZ_CUCUTA"."@GD_SUBGRUPO" T9
		ON T7."U_GD_SubGrupo" = T9."Code"
LEFT JOIN
	"HBTGELVEZ_CUCUTA"."@GD_FAMPRODUCTOS" T10
		ON T7."U_GD_FamProducto" = T10."Code"
--	VENDEDOR
INNER JOIN
	"HBTGELVEZ_CUCUTA"."OSLP" T11
		ON T1."SlpCode" = T11."SlpCode"
WHERE
--T1."DocDate" BETWEEN '[%0]' AND '[%1]'
T1."DocDate" BETWEEN {0}--ADD_DAYS(LAST_DAY(ADD_MONTHS(CURRENT_DATE, -{0})),+1) AND  ADD_DAYS(TO_VARCHAR(CURRENT_DATE,'YYYYMMDD'), -1 )
AND T2."WhsCode" in ('006', '030')) AS "TA"

-- UNION PARA MONTAR LA SALIDAD DE DATOS DE GRAN DISTRIBUIDOR.
UNION ALL 

SELECT DISTINCT * FROM(SELECT
	DISTINCT
	--	CLIENTE
	(T1."CardCode" || '#'  ||
	IFNULL(T3."BlockS",'SIN BARRIO') || '#' ||
IFNULL(T5."U_HBT_MunMed",'54001')) AS "Clientes"
--	DOCUMENTO
FROM
	"HBTGRANDISTRIBUIDOR"."OINV" T1
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."INV1" T2
		ON T1."DocEntry" = T2."DocEntry"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."INV12" T3
		ON T1."DocEntry" = T3."DocEntry"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."NNM1" T4
		ON T1."Series" = T4."Series"
--	CLIENTE
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OCRD" T5
		ON T1."CardCode" = T5."CardCode"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OCRG" T6
		ON T5."GroupCode" = T6."GroupCode"
--	PRODUCTO
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OITM" T7
		ON T2."ItemCode" = T7."ItemCode"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OITB" T8
		ON T7."ItmsGrpCod" = T8."ItmsGrpCod"
LEFT JOIN
	"HBTGRANDISTRIBUIDOR"."@GD_SUBGRUPO" T9
		ON T7."U_GD_SubGrupo" = T9."Code"
LEFT JOIN
	"HBTGRANDISTRIBUIDOR"."@GD_FAMPRODUCTOS" T10
		ON T7."U_GD_FamProducto" = T10."Code"
--	VENDEDOR
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OSLP" T11
		ON T1."SlpCode" = T11."SlpCode"
WHERE
--T1."DocDate" BETWEEN '[%0]' AND '[%1]'
T1."DocDate" BETWEEN {0}--ADD_DAYS(LAST_DAY(ADD_MONTHS(CURRENT_DATE, -{0})),+1) AND  ADD_DAYS(TO_VARCHAR(CURRENT_DATE,'YYYYMMDD'), -1 )
AND T2."WhsCode" IN ('010','014','019')

UNION ALL

SELECT
	DISTINCT
	--	CLIENTE
	(T1."CardCode" || '#'  ||
	IFNULL(T3."BlockS",'SIN BARRIO') || '#' ||
IFNULL(T5."U_HBT_MunMed",'54001')) AS "Clientes"
--	DOCUMENTO
FROM
	"HBTGRANDISTRIBUIDOR"."ORIN" T1
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."RIN1" T2
		ON T1."DocEntry" = T2."DocEntry"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."RIN12" T3
		ON T1."DocEntry" = T3."DocEntry"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."NNM1" T4
		ON T1."Series" = T4."Series"
--	CLIENTE
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OCRD" T5
		ON T1."CardCode" = T5."CardCode"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OCRG" T6
		ON T5."GroupCode" = T6."GroupCode"
--	PRODUCTO
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OITM" T7
		ON T2."ItemCode" = T7."ItemCode"
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OITB" T8
		ON T7."ItmsGrpCod" = T8."ItmsGrpCod"
LEFT JOIN
	"HBTGRANDISTRIBUIDOR"."@GD_SUBGRUPO" T9
		ON T7."U_GD_SubGrupo" = T9."Code"
LEFT JOIN
	"HBTGRANDISTRIBUIDOR"."@GD_FAMPRODUCTOS" T10
		ON T7."U_GD_FamProducto" = T10."Code"
--	VENDEDOR
INNER JOIN
	"HBTGRANDISTRIBUIDOR"."OSLP" T11
		ON T1."SlpCode" = T11."SlpCode"
WHERE
--T1."DocDate" BETWEEN '[%0]' AND '[%1]'
T1."DocDate" BETWEEN {0}--ADD_DAYS(LAST_DAY(ADD_MONTHS(CURRENT_DATE, -{0})),+1) AND  ADD_DAYS(TO_VARCHAR(CURRENT_DATE,'YYYYMMDD'), -1 )
AND T2."WhsCode" in ('010','014','019')) AS "TA"

